const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
document.addEventListener("DOMContentLoaded",()=>{
 const dep=$("#departure"); if(dep){const d=new Date();d.setDate(d.getDate()+7);dep.value=d.toISOString().slice(0,10);const ret=$("#returnDate");if(ret){const r=new Date(d);r.setDate(r.getDate()+7);ret.value=r.toISOString().slice(0,10)}}
 const swap=$("#swap");if(swap)swap.onclick=()=>{const a=$("#from").value;$("#from").value=$("#to").value;$("#to").value=a};
 $$(".tab").forEach(t=>t.onclick=()=>{$$(".tab").forEach(x=>x.classList.remove("active"));t.classList.add("active")});
 const form=$("#searchForm");if(form)form.onsubmit=e=>{e.preventDefault();localStorage.setItem("veyoraSearch",JSON.stringify({from:$("#from").value,to:$("#to").value,travellers:$("#travellers").value,departure:$("#departure").value}));location.href="results.html"};
 if($("#resultList"))renderResults();
 if($("#bookingForm"))$("#bookingForm").onsubmit=e=>{e.preventDefault();const s=JSON.parse(localStorage.getItem("veyoraSearch")||'{"from":"Hyderabad (HYD)","to":"Delhi (DEL)","travellers":"1 Traveller"}');const booking={id:"VY"+Date.now().toString().slice(-6),name:$("#name").value,email:$("#email").value,phone:$("#phone").value,seat:$("#seat").value,...s};const trips=JSON.parse(localStorage.getItem("veyoraTrips")||"[]");trips.unshift(booking);localStorage.setItem("veyoraTrips",JSON.stringify(trips));alert("Booking confirmed! Your booking ID is "+booking.id);location.href="trips.html"};
 if($("#trips"))renderTrips();
});
function renderResults(){const s=JSON.parse(localStorage.getItem("veyoraSearch")||'{"from":"Hyderabad (HYD)","to":"Delhi (DEL)","travellers":"1 Traveller"}');$("#routeTitle").textContent=s.from+" → "+s.to;$("#searchSummary").textContent=(s.travellers||"1 Traveller")+" · Economy";const flights=[["06:10","08:25","2h 15m","₹5,499"],["10:40","13:00","2h 20m","₹6,199"],["18:30","20:45","2h 15m","₹5,899"]];$("#resultList").innerHTML=flights.map((f,i)=>`<div class="result-card"><div class="flight-info"><div><strong>${f[0]}</strong><div class="muted">${s.from}</div></div><div class="muted">— ${f[2]} —</div><div><strong>${f[1]}</strong><div class="muted">${s.to}</div></div></div><div><div class="price">${f[3]}</div><button class="search-btn" onclick="location.href='booking.html'">Select</button></div></div>`).join("")}
function renderTrips(){const trips=JSON.parse(localStorage.getItem("veyoraTrips")||"[]");$("#trips").innerHTML=trips.length?trips.map(t=>`<div class="trip-card"><div><span class="eyebrow">${t.id}</span><h3>${t.from} → ${t.to}</h3><p class="muted">${t.name} · ${t.travellers||"1 Traveller"} · ${t.seat} seat · ${t.email}</p></div><b>Confirmed ✓</b></div>`).join(""):`<div class="trip-card"><div><h3>No trips yet</h3><p class="muted">Search for a journey and complete a demo booking.</p></div><a class="search-btn inline" href="index.html#booking">Start booking</a></div>`}